In [1]:
import pandas as pd
import json

In [2]:
data = pd.read_csv("/home/anni/Schreibtisch/2023-2024-Data-Librarian-AKC/Modul_3/data/Library_Usage.csv")

/tmp/ipykernel_1035736/3676822830.py:1: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("/home/anni/Schreibtisch/2023-2024-Data-Librarian-AKC/Modul_3/data/Library_Usage.csv")

In [3]:
data

,Patron Type Code,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Code,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Code,Notice Preference Definition,Provided Email Address,Year Patron Registered,Within San Francisco County
0,5,Staff,53,15,NaN,b2,Bayview,Mar,2023.0,z,Email,True,2003,False
1,5,Staff,480,378,NaN,e9,Excelsior,Jun,2023.0,z,Email,True,2003,False
2,5,Staff,70,33,45 to 54 years,n4,Noe Valley,Jan,2023.0,z,Email,True,2011,False
3,5,Staff,3934,2140,NaN,o2,Ocean View,Jul,2023.0,z,Email,True,2003,False
4,5,Staff,1118,1035,NaN,o7,Ortega,Jul,2023.0,z,Email,True,2003,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
436285,0,Adult,2,6,35 to 44 years,yjj,Bookmobile,Oct,2022.0,z,Email,True,2020,NaN
436286,2,Teen,3,0,10 to 19 years,yjj,Bookmobile,Nov,2015.0,z,Email,True,2011,NaN
436287,0,Adult,6,0,60 to 64 years,ylw,Bookmobile,Mar,2022.0,z,Email,True,2022,NaN
436288,15,Teacher Card,4,0,35 to 44 years,ylw,Bookmobile,Sep,2020.0,z,Email,True,2019,NaN
436289,55,Retired Staff,309,101,75 years and over,ylw,Bookmobile,Jul,2023.0,z,Email,True,2003,NaN

In [4]:
data.columns

Index(['Patron Type Code', 'Patron Type Definition', 'Total Checkouts',
       'Total Renewals', 'Age Range', 'Home Library Code',
       'Home Library Definition', 'Circulation Active Month',
       'Circulation Active Year', 'Notice Preference Code',
       'Notice Preference Definition', 'Provided Email Address',
       'Year Patron Registered', 'Within San Francisco County'],
      dtype='object')

In [5]:
age_filter = (data['Age Range'] == '60 to 64 years')

In [9]:
filtered_age = data.loc[age_filter]

In [10]:
filtered_age

,Patron Type Code,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Code,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Code,Notice Preference Definition,Provided Email Address,Year Patron Registered,Within San Francisco County
11,5,Staff,146,259,60 to 64 years,x,Main,Jul,2023.0,z,Email,True,2008,False
26,5,Staff,843,234,60 to 64 years,x,Main,Jun,2020.0,z,Email,True,2003,False
48,0,Adult,41,18,60 to 64 years,m2,Marina,Mar,2023.0,z,Email,True,2022,False
90,0,Adult,0,0,60 to 64 years,x,Main,Aug,2022.0,z,Email,True,2018,False
137,16,Digital Access Card,0,0,60 to 64 years,x,Main,Nov,2021.0,z,Email,True,2021,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
436197,0,Adult,0,0,60 to 64 years,x,Main,Jun,2023.0,z,Email,True,2014,NaN
436217,0,Adult,0,0,60 to 64 years,x,Main,NaN,NaN,z,Email,True,2021,NaN
436236,0,Adult,2,0,60 to 64 years,x,Main,Mar,2023.0,NaN,NaN,False,2022,NaN
436260,0,Adult,172,178,60 to 64 years,x,Main,Jul,2023.0,NaN,NaN,False,2022,NaN
436287,0,Adult,6,0,60 to 64 years,ylw,Bookmobile,Mar,2022.0,z,Email,True,2022,NaN

In [7]:
data['Circulation Active Year'].unique()

array([2023., 2020., 2018., 2022., 2019., 2021.,   nan, 2017., 2014.,
       2011., 2009., 2016., 2015., 2007., 2013., 2010., 2012., 2006.,
       2005., 2008., 2004.])

In [ ]:
filtered_age['Circulation Active Year'] == 'Richmond')

0         False
1         False
2         False
3         False
4         False
          ...
436285    False
436286    False
436287     True
436288    False
436289    False
Name: Age Range, Length: 436290, dtype: bool

In [ ]:
data.loc[loc_filter]